name = "klub-kgb"
main = ".svelte-kit/cloudflare-workers/index.js"
compatibility_date = "2025-09-16"

# Static assets
[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

# Environment variables for your app
[vars]
PUBLIC_LANDING_DIRECTUS_URL = "https://cms.cloverlabs.dev"
PUBLIC_LANDING_DIRECTUS_COLLECTION_NAME = "kgb-posts"
PUBLIC_APP_NAME = "klub-kgb"

# Workers Logs
[observability]
enabled = true