name = "klub-kgb"
compatibility_date = "2025-09-16"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Environment variables for your app
[vars]
PUBLIC_LANDING_DIRECTUS_URL = "https://cms.cloverlabs.dev"
PUBLIC_LANDING_DIRECTUS_COLLECTION_NAME = "kgb-posts"
PUBLIC_APP_NAME = "klub-kgb"

# Workers Logs
[observability]
enabled = true